langchain-ai/open-agent-platform

apps/web/src/types/configurable.ts

Proposal for the type interface of configurable fields.

feat: Add type for configurable items

---

apps/web/package.json
apps/web/src/components/tools/components/tool-card/index.tsx
apps/web/src/components/tools/components/tool-details-dialog/index.tsx
apps/web/src/components/tools/components/tool-details-dialog/schema-renderer.tsx
apps/web/src/components/tools/dummy.ts
apps/web/src/components/tools/index.tsx
apps/web/src/components/ui/badge.tsx
apps/web/src/components/ui/button.tsx
apps/web/src/components/ui/tooltip-icon-button.tsx
apps/web/src/hooks/use-mcp.tsx
apps/web/src/types/tool.ts
yarn.lock

feat: Tool details page

---

apps/web/src/components/agents/components/agent-card/index.tsx
apps/web/src/components/agents/index.tsx

Agents now scroll along the x axis instead of wrapping

fix: Handle large numbers of agents in UI

---

apps/web/package.json
apps/web/src/components/ui/alert-dialog.tsx
apps/web/src/features/agents/components/agent-card/index.tsx
apps/web/src/features/agents/components/create-agent-dialog/index.tsx
apps/web/src/features/agents/index.tsx
apps/web/src/features/chat/components/configuration-sidebar/config-field.tsx
apps/web/src/features/chat/components/configuration-sidebar/index.tsx
apps/web/src/hooks/use-agents.tsx
apps/web/src/providers/Agents.tsx
yarn.lock

feat: Add create agent dialog

---

apps/web/src/features/agents/components/agent-form/index.tsx
apps/web/src/features/agents/components/create-agent-dialog/index.tsx
apps/web/src/features/agents/components/edit-agent-dialog/index.tsx
apps/web/src/features/agents/index.tsx
apps/web/src/features/chat/components/configuration-sidebar/config-field.tsx
apps/web/src/features/chat/components/configuration-sidebar/index.tsx
apps/web/src/features/chat/hooks/use-config-store.tsx
apps/web/src/hooks/use-agents.tsx

fix: Ensure config side panel reads proper values

---

apps/web/src/components/ui/agents-combobox.tsx

fix: Agents grouped by deployments > graphs > agents in combobox

---

apps/web/src/components/ui/pagination.tsx
apps/web/src/components/ui/table.tsx
apps/web/src/features/rag/components/collections-card/index.tsx
apps/web/src/features/rag/components/collections-list/index.tsx
apps/web/src/features/rag/components/documents-card/documents-table.tsx
apps/web/src/features/rag/components/documents-card/index.tsx
apps/web/src/features/rag/hooks/use-collections.tsx
apps/web/src/features/rag/hooks/use-documents.tsx
apps/web/src/features/rag/index.tsx
apps/web/src/types/collection.ts

feat: RAG page

---

apps/web/src/features/rag/components/collections-card/index.tsx
apps/web/src/features/rag/components/documents-card/documents-table.tsx
apps/web/src/features/rag/components/documents-card/index.tsx

feat: Implement loading states in RAG page

---

apps/web/package.json
apps/web/src/app/api/oap_mcp/proxy-request.ts
apps/web/src/app/api/oap_mcp/route.ts
apps/web/src/components/sidebar/index.tsx
apps/web/src/components/ui/tool-search.tsx
apps/web/src/features/agents/components/agent-form/index.tsx
apps/web/src/features/agents/components/create-agent-dialog/index.tsx
apps/web/src/features/agents/components/edit-agent-dialog/index.tsx
apps/web/src/features/chat/components/configuration-sidebar/config-field.tsx
apps/web/src/features/chat/components/configuration-sidebar/index.tsx
apps/web/src/features/chat/hooks/use-config-store.tsx
apps/web/src/features/tools/components/tool-card/index.tsx
apps/web/src/features/tools/index.tsx
apps/web/src/hooks/use-mcp.tsx
apps/web/src/lib/ui-config.ts
apps/web/src/providers/MCP.tsx
apps/web/src/types/configurable.ts
yarn.lock

fix: Hookup tools

---

apps/web/src/app/tools/playground/page.tsx
apps/web/src/features/agents/components/create-edit-agent-dialogs/create-agent-dialog.tsx
apps/web/src/features/agents/components/create-edit-agent-dialogs/edit-agent-dialog.tsx
apps/web/src/features/rag/components/documents-card/index.tsx
apps/web/src/features/tools/components/tool-card/index.tsx
apps/web/src/features/tools/components/tool-details-dialog/index.tsx
apps/web/src/features/tools/components/tool-list-command.tsx
apps/web/src/features/tools/index.tsx
apps/web/src/features/tools/playground/components/response-viewer.tsx
apps/web/src/features/tools/playground/components/schema-form.tsx
apps/web/src/features/tools/playground/index.tsx
apps/web/src/hooks/use-mcp.tsx
apps/web/src/providers/MCP.tsx

feat: Tools playground

---

apps/web/src/features/chat/components/configuration-sidebar/index.tsx
apps/web/src/features/chat/components/sidebar-buttons/index.tsx
apps/web/src/features/chat/components/thread-history-sidebar/index.tsx
apps/web/src/features/chat/index.tsx

feat: Close sidebars on outside click

---

apps/web/src/components/sidebar/sidebar-header.tsx

fix: Sidebar logo sizing

---

apps/web/src/components/ui/agents-combobox.tsx

fix: Hide default agents in combobox

---

apps/web/src/features/agents/components/create-edit-agent-dialogs/agent-form.tsx
apps/web/src/features/chat/components/configuration-sidebar/index.tsx
apps/web/src/features/tools/components/tool-list-command.tsx
apps/web/src/hooks/use-fetch-preselected-tools.tsx
apps/web/src/hooks/use-search-tools.tsx

feat: Always show selected tools

---

apps/web/src/features/agents/components/agent-card.tsx

fix: dont open new tab when clicking chat

---

apps/web/src/features/tools/index.tsx

fix: Add a plus next to tools count if has more is true

---

apps/web/src/components/ui/agents-combobox.tsx
apps/web/src/features/chat/components/chat-breadcrumb/index.tsx
apps/web/src/features/chat/components/configuration-sidebar/config-field.tsx
apps/web/src/features/chat/providers/Stream.tsx

fix: Add loading spinner to agents combobox

---

apps/web/scripts/update-agents-mcp-url.ts
apps/web/src/components/ui/agents-combobox.tsx
apps/web/src/features/chat/components/configuration-sidebar/index.tsx
apps/web/src/features/chat/index.tsx
apps/web/src/features/chat/providers/Stream.tsx
apps/web/src/hooks/use-agent-config.tsx
apps/web/src/lib/agent-utils.ts

feat: Add support for default agents

---

README.md
apps/web/src/lib/agent-utils.ts
apps/web/src/providers/Agents.tsx
apps/web/src/types/deployment.ts

fix: Better default agent config

---

apps/web/src/features/rag/components/collections-card/index.tsx
apps/web/src/features/rag/components/collections-list/edit-collection-dialog.tsx

feat: Add character limit to collection description

---

README.md
apps/web/scripts/update-agents-mcp-url.ts
apps/web/src/app/api/oap_mcp/proxy-request.ts
apps/web/src/hooks/use-mcp.tsx
apps/web/src/lib/ui-config.ts

fix: Better auth/unauthed mcp server support

---

README.md
apps/web/src/lib/agent-utils.ts
apps/web/src/providers/Agents.tsx
apps/web/src/types/deployment.ts

fixes #174
TODO: Ensure docs is clear

fix: primary graph identifier

---

apps/web/.env.example
apps/web/src/lib/environment/tools.ts

chore: Update env example

---

apps/web/src/app/(app)/agents/page.tsx
apps/web/src/app/(app)/inbox/page.tsx
apps/web/src/app/(app)/page.tsx
apps/web/src/app/(app)/rag/page.tsx
apps/web/src/app/(app)/tools/page.tsx
apps/web/src/app/(app)/tools/playground/page.tsx
apps/web/src/components/ui/agents-combobox.tsx
apps/web/src/components/ui/alert-dialog.tsx
apps/web/src/components/ui/markdown-text/index.tsx
apps/web/src/features/agents/components/agent-card.tsx
apps/web/src/features/agents/components/create-edit-agent-dialogs/agent-form.tsx
apps/web/src/features/agents/components/create-edit-agent-dialogs/create-agent-dialog.tsx
apps/web/src/features/agents/components/create-edit-agent-dialogs/edit-agent-dialog.tsx
apps/web/src/features/chat/components/chat-breadcrumb/index.tsx
apps/web/src/features/chat/components/sidebar-buttons/index.tsx
apps/web/src/features/chat/components/thread/index.tsx
apps/web/src/features/chat/components/thread/messages/ai.tsx
apps/web/src/features/chat/components/thread/messages/human.tsx
apps/web/src/features/chat/providers/Stream.tsx
apps/web/src/features/tools/components/tool-card/index.tsx
apps/web/src/features/tools/index.tsx
apps/web/src/hooks/use-agent-config.tsx
apps/web/src/hooks/use-agents.tsx
package.json
yarn.lock

- use `react-hook-form` to re-render as little as possible
- switch to uncontrolled state to avoid rerendering whole thread while typing input

feat: avoid unnecessary rerenders, additional UX nits

---

README.md
apps/web/src/lib/ui-config.ts

fix: rename x_lg_ui_config to x_oap_ui_config

---

README.md
apps/web/scripts/update-agents-mcp-url.ts
apps/web/src/lib/ui-config.ts
apps/web/src/types/configurable.ts

chore: Document mcp server url updater script

---

apps/web/src/features/rag/components/documents-card/index.tsx
apps/web/src/hooks/use-agent-config.tsx
apps/web/src/lib/agent-utils.ts

feat: Chat with collection

---

apps/web/src/features/chat/components/thread/index.tsx

Before: We snap back to empty chat on refresh
https://github.com/user-attachments/assets/8db54037-e322-4d1e-862a-d4aea274cff7
After: Show loading message on refresh, a bit cleaner
https://github.com/user-attachments/assets/b2267a9d-c65b-40a6-854f-74392d1f9f46

nit: Add loading state for chat instead of cutting to empty chat

---

apps/web/src/app/(app)/page.tsx
apps/web/src/app/(app)/rag/page.tsx
apps/web/src/components/sidebar/index.tsx
apps/web/src/features/rag/hooks/use-rag.tsx
apps/web/src/features/rag/index.tsx

previously, whenever going to any page i was seeing a `/collections` failure in the network tab. this PR makes the fetches to the rag service conditional on whether it's set in `.env`. 
tested this by going to the rag page -> looking at api calls, and fixes constantly having the error in the network tab

update: fix rag fetch

---

apps/web/src/features/deep-agent-chat/components/ChatInterface.tsx
apps/web/src/features/deep-agent-chat/components/OptimizationWindow.tsx
apps/web/src/features/deep-agent-chat/components/TasksFilesSidebar.tsx
apps/web/src/features/deep-agent-chat/index.tsx
apps/web/src/features/deep-agent-chat/providers/ChatContext.tsx
apps/web/src/features/deep-agent-chat/providers/ChatProvider.tsx

Also fixed a few dependency arrays

Add a provider for useChat

---

apps/web-v2/src/features/triggers/components/registrations-hover-card.tsx
apps/web-v2/src/features/triggers/components/trigger-accordion-item.tsx

small quality of life improvement so people can see triggers registered

feat: show triggers

---

apps/web/src/app/(app)/agents/chat/page.tsx
apps/web/src/components/ui/select.tsx
apps/web/src/features/agents/utils.ts
apps/web/src/features/chat/components/thread-history-agent-list.tsx
apps/web/src/features/chat/types.ts
apps/web/src/features/chat/utils.ts
packages/deep-agent-chat/src/DeepAgentChatInterface.tsx
packages/deep-agent-chat/src/components/ChatInterface.tsx
packages/deep-agent-chat/src/components/TasksFilesSidebar.tsx

- reduce number of states of sidebar
- sync sidebar state with agent picker state

feat: improve chat screen (v3)
